layout: sidebar
style: dark
theme: jekyll-theme-hacker
plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

repository : SupragyaVS/SupragyaVS.github.io

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects: 
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  hackerrank: http://www.hackerearth.com/@Supragya24
  hackaday: https://hackaday.io/SupragyaVS
  # instagram: your_username
  # keybase: your_username
  linkedin: Supragya Vikram Singh
  # mastodon: your_username
  # medium: your_username
  stackoverflow: 13715634
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  website: http://SupragyaVS.github.io
  # youtube: your_username

topics:
  - name: C
    web_url: https://github.com/topics/c-language
    image_url: https://www.pngitem.com/pimgs/m/31-312155_c-programming-language-logo-hd-png-download.png
    
  - name: Applications of Python 
    web_url: https://github.com/python
    image_url: https://avatars0.githubusercontent.com/u/1525981?s=200&v=4

  - name: Game Development using Unity3D Engine
    web_url: https://github.com/Unity-Technologies
    image_url : https://avatars1.githubusercontent.com/u/426196?s=200&v=4
